import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import hridoy from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white overflow-hidden px-10 md:px-20 lg:px-40  dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white ">
              khandakar-hridoy
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 "
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-semibold md:text-6xl">
              Hridoy Khandakar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 cursor-pointer text-gray-600 dark:text-white">
            <AiFillLinkedin />
            <AiFillGithub />
            <AiFillTwitterCircle />
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto my-20 overflow-hidden md:h-96 md:w-96">
            <Image className="object-fill h-full" src={hridoy} />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-2 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-6">
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:text-white dark:bg-slate-800 ">
              <Image
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-xl font-medium pt-8 pb2">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="text-lg py-4 text-teal-600 ">
                Design Tools I Use
              </h4>
              <div className="flex gap-2 justify-center">
                <p className="bg-teal-600 rounded-full text-xs text-white p-2 ">
                  Photoshop
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Illustrator
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Figma
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Indesign
                </p>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:text-white dark:bg-slate-800 ">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-xl font-medium pt-8 pb2">Code</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="text-lg py-4 text-teal-600">Design Tools I Use</h4>
              <div className="flex gap-2 justify-center">
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Photoshop
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Illustrator
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Figma
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Indesign
                </p>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:text-white dark:bg-slate-800 ">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-xl font-medium pt-8 pb2">Beautiful Design</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="text-lg py-4 text-teal-600">Design Tools I Use</h4>
              <div className="flex gap-2 justify-center">
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Photoshop
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Illustrator
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Figma
                </p>
                <p className="bg-teal-600 rounded-full text-xs text-white p-2">
                  Indesign
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-2 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 dark:text-white">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col py-10 gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web3}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"100%"}
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
